### ISSUE TITLE
How to remove Icons from .zshrc

### ISSUE THREAD

**Issue by theasteve** [sudhindrasajjal/dotfiles#2]
<img width="1434" alt="Screen Shot 2019-04-22 at 10 22 04 AM" src="https://user-images.githubusercontent.com/14843767/56505081-95354f80-64e8-11e9-9e28-bb4d6c92d725.png">

I would like to remove the `icons` from the terminal. How can I go about doing that so I wont have the question marks as shown in the picture?

**Comment by sudhindrasajjal** [comment]
Hey, sorry for the extremely delayed response, you can find all the icons at .oh-my-zsh/themes/powerlevel9k/functions/icons.zsh. You can comment out whatever is not required
