### ISSUE TITLE
Roboto Mono for Powerline + Knack Regular Nerd Font 

### ISSUE THREAD

**Issue by keepscoding** [sudhindrasajjal/dotfiles#3]
where do u get this merged font? can u share?

**Comment by chadspring** [comment]
where do u get this merged font? can u share?

**Comment by keepscoding** [comment]
Actually u dont need to merge them. 
My bad, i didn't realise there is another font selection (Non-ASCII font) right after font selection.
So, first u select **Roboto Mono for Powerline** for _font selection_.
Then, u select **Knack Regular Nerd Font** for _Non-ASCII font_.
