### ISSUE TITLE
How to get correct arrows in newline?

### ISSUE THREAD

**Issue by pietrofxq** [sudhindrasajjal/dotfiles#4]
The current configuration gives me this look on the newline:

![image](https://user-images.githubusercontent.com/6238029/63204758-72343a00-c09b-11e9-9ca2-8cba13f88fdb.png)

How to make it show the proper arrows with colors?

**Comment by sudhindrasajjal** [comment]
Hi, sorry for the extremely delayed response, but you need to have nerd fonts installed, this looks like font awesome if I am not mistaken.
